/**
 * Generates public/firebase-messaging-sw.js from NEXT_PUBLIC_FIREBASE_* env vars.
 * Keeps the background push handler in sync with the main app Firebase config.
 */
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const config = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY || '',
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || '',
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || '',
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || '',
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || '',
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID || '',
  measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID || '',
};

const output = `/* Auto-generated by scripts/generate-fcm-sw.mjs — do not edit manually */
importScripts('https://www.gstatic.com/firebasejs/11.0.2/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/11.0.2/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(config, null, 2)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const title = payload.notification?.title || payload.data?.title || 'SpeakUp GC';
  const body = payload.notification?.body || payload.data?.body || payload.data?.message || '';
  const actionUrl = payload.data?.actionUrl || payload.fcmOptions?.link || '/notifications';
  const tag = payload.data?.notificationId || payload.data?.tag || 'speakup-gc';

  self.registration.showNotification(title, {
    body,
    icon: '/icon-192x192.png',
    badge: '/icon-192x192.png',
    tag,
    renotify: true,
    data: { actionUrl, ...(payload.data || {}) },
    vibrate: [120, 60, 120],
  });
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const target = event.notification.data?.actionUrl || '/notifications';
  const url = new URL(target, self.location.origin).href;

  event.waitUntil(
    (async () => {
      const clientsList = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
      for (const client of clientsList) {
        if ('focus' in client) {
          await client.focus();
          if ('navigate' in client) {
            try {
              await client.navigate(url);
            } catch (_) {
              /* older browsers */
            }
          }
          return;
        }
      }
      if (self.clients.openWindow) {
        await self.clients.openWindow(url);
      }
    })()
  );
});
`;

const outPath = join(__dirname, '../public/firebase-messaging-sw.js');
writeFileSync(outPath, output, 'utf8');
console.log('[generate-fcm-sw] Wrote', outPath, 'projectId:', config.projectId || '(missing)');
